config/routes.rb
Rails.application.routes.draw do
  resources :pokemons
  root 'home#index'

  devise_for :users, controllers: {registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks"}
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  resourcify

  belongs_to :user
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource only: [:index]
  skip_load_and_authorize_resource only: [:new, :create]
  def index

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @pokemons }
    end
  end
  def show
    @pokemon = Pokemon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: '/' }
    end
  end
  def new
    @user = params[:user_id]
    @pokemon = Pokemon.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @pokemon }
    end
  end
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        flash[:notice] = 'Pokemon was successfully created.'
        format.html { redirect_to(@pokemon) }
        format.xml  { render xml: @pokemon, status: :created, location: @pokemon }
      else
        format.html { render action: 'new' }
        format.xml  { render xml: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end
  def edit
    @user = params[:user_id]
    @pokemon = Pokemon.find(params[:id])
  end

  def update
    @pokemon = Pokemon.find(params[:id])

    respond_to do |format|
      if @pokemon.update(pokemon_params)
        flash[:notice] = 'Pokemon was successfully updated.'
        format.html { redirect_to(@pokemon) }
        format.xml  { head :ok }
      else
        format.html { render action: 'edit' }
        format.xml  { render xml: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @pokemon = Pokemon.find(params[:id])
    @pokemon.destroy

    respond_to do |format|
      format.html { redirect_to(pokemons_url) }
      format.xml  { head :ok }
    end
  end
  
  private

  def pokemon_params
    params.require(:pokemon).permit(:name, :cp, :user_id)
  end
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/pokemons/_form.html.erb
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :cp %>
<%= f.number_field :cp %>
<%= f.hidden_field :user_id, value: @user.to_i %>
<%= f.submit %>

app/views/pokemons/_list.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>주인</th>
      <th>CP</th>
      <th>정보보기</th>
      <th>포켓몬 정보 변경</th>
      <th>포켓몬 제거</th>
    </tr>
  </thead>
  <tbody>
    <% pokemons.each do |p| %>
      <tr>
        <td><%= p.name %></td>
        <td><%= p.user.name %></td>
        <td><%= p.cp %></td>
        <td><%= link_to "보기", pokemon_path(p.id) %></td>
        <td><%= link_to "변경", edit_pokemon_path(p.id, user_id: current_user) %></td>
        <td><%= link_to "삭제", pokemon_path(p.id), method: "DELETE" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pokemons/edit.html.erb
<%= form_for @pokemon do |f| %>
  <%= render partial: 'pokemons/form', locals: { f: f } %>
<% end %>

app/views/pokemons/index.html.erb
<div class="row text-center">
  <h1>Pokemon List</h1>
  <%= link_to "뒤로가기", root_path, class: "btn btn-default" %>
  <% if flash[:warning].present? %>
    <%= content_tag :div, flash[:warning] %>
  <% end %>
</div>
<% if user_signed_in? %>
  <p> <%= current_user.name %></p>
  <p> <%=current_user.roles.first.name %></p>
      <%= render partial: 'pokemons/list', locals: {pokemons: @pokemons } %>
<% end %>

app/views/pokemons/new.html.erb
<%= form_for @pokemon do |f| %>
  <%= render partial: 'pokemons/form', locals: { f: f } %>
<% end %>

app/views/pokemons/show.html.erb
<%= @pokemon.name %><br/>
<%= @pokemon.cp %><br/>
<%= link_to "돌아가기", '/', class: "btn btn-default" %>